on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - run: sudo apt install -y cmake
      - run: mkdir build
      - run: cmake -B build
      - run: make --directory build
      - run: sudo make --directory build install

  Linux-Musl-QEMU:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - i386
          - s390x   # Test big-endian
          - arm32v6
          - arm32v7

    steps:
      - uses: actions/checkout@main
      - name: Get the qemu container
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: ${{ matrix.platform }}
        run: docker run --rm --interactive --mount type=bind,source=$(pwd),target=/host ${{ matrix.platform }}/alpine sh -c "apk add cmake make gcc libc-dev git; cp -r /host from-host; cd from-host; mkdir build; cmake -B build; make --directory build install"

  macOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - run: brew install cmake
      - run: mkdir build
      - run: cmake -B build
      - run: make --directory build install

